fix: unable to play music
Nat1anWasTaken/Lava pull request #168
Opened 2024-08-24 16:01 UTC by Mantouisyummy

This PR not only fixes the issue where music couldn't be played
also adds new setup instructions in the Readme.md, using Pterodactyl egg to achieve it.

2024-08-24 16:48 UTC, ads19740119 commented
是否解決?

2024-08-24 16:57 UTC, Mantouisyummy commented
> 是否解決?

理論上這個PR可以解決此問題。
如同這個PR的介紹，由於YT的動作導致需要提供poToken這種東西，才能夠正常運作。

2024-08-24 17:00 UTC, ads19740119 commented
可以加DC嗎
?


Mantouisyummy ***@***.***> 於 2024年8月25日 週日 上午12:57寫道：

> 是否解決?
>
> 理論上這個PR可以解決此問題。
> 如同這個PR的介紹，由於YT的動作導致需要提供poToken這種東西，才能夠正常運作。
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Nat1anWasTaken/Lava/pull/168#issuecomment-2308455932>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKVMSJFMJYHSAJLDCCMNQC3ZTC3QPAVCNFSM6AAAAABNBWNGQSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMBYGQ2TKOJTGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-08-24 17:00 UTC, ads19740119 commented
有些不懂的地方

Aa App ***@***.***> 於 2024年8月25日 週日 上午1:00寫道：

> 可以加DC嗎
> ?
>
>
> Mantouisyummy ***@***.***> 於 2024年8月25日 週日 上午12:57寫道：
>
>> 是否解決?
>>
>> 理論上這個PR可以解決此問題。
>> 如同這個PR的介紹，由於YT的動作導致需要提供poToken這種東西，才能夠正常運作。
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Nat1anWasTaken/Lava/pull/168#issuecomment-2308455932>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AKVMSJFMJYHSAJLDCCMNQC3ZTC3QPAVCNFSM6AAAAABNBWNGQSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMBYGQ2TKOJTGI>
>> .
>> You are receiving this because you commented.Message ID:
>> ***@***.***>
>>
>

2024-08-24 17:03 UTC, Mantouisyummy commented
> 有些不懂的地方
> 可以加DC嗎 ?

您可以到 https://discord.com/invite/3y7mN82NQa
這是Lava的支援群組詢問，不過我們並沒有特別宣傳此群組

2024-08-25 01:27 UTC, Nat1anWasTaken requested changes

2024-08-25 01:27 UTC, Nat1anWasTaken commented on README.md
Consider using "YouTube" instead of "Youtube".

2024-08-25 01:27 UTC, Nat1anWasTaken commented on README.md
> +## Lavalink 配置
Maybe add some instructions on how to run the script? Like a python command. Or, `docker run` to run the script inside the environment of the image.

2024-08-25 01:27 UTC, Nat1anWasTaken commented on poToken_generator.py
Me at the zoo 🤔

2024-08-25 01:38 UTC, Mantouisyummy commented on poToken_generator.py
🐒🦧

2024-08-25 01:38 UTC, Mantouisyummy commented on README.md
lmao ok
kekw

2024-08-25 05:36 UTC, Nat1anWasTaken approved these changes
LGTM.

2024-08-25 05:36 UTC, merged